hwo to create a video clarify
noxonsu/tools.onout.org pull request #43
Opened 2022-04-29 09:47 UTC by noxonsu

2022-04-29 10:03 UTC, VitaliyShulik commented on contributing.md
> +Видос залить в в наш канал https://www.youtube.com/channel/UCEu5-QDPFCxKm9z4BAYQSJw (логин support@oout.org). Создать новый плейлист.
support@onout.org

2022-04-29 10:09 UTC, VitaliyShulik approved these changes

2022-05-04 13:41 UTC, jsohex requested changes

2022-05-04 13:41 UTC, jsohex commented on contributing.md
> +название видео "How to create a DEX without codeing skills at your own domain. Uniswap v2 fork (copy) tutorial". названия меняем. обязательно как можно больше ключей (см семантика п. 1)
```suggestion
Название видео: "How to create a DEX on your own domain without coding skills. Uniswap v2 fork (copy) tutorial". Названия меняем в соответствии со своим продуктом. 
Обязательно использовать как можно больше ключевых слов (см семантика п. 1)
```

2022-05-04 13:41 UTC, jsohex commented on contributing.md
> +## 2. записать видос (вы записываете на английском).
```suggestion
## 2. Записать видео (на английском).
Вы записываете либо своим голосом (желательно без слов паразитов и длинных пауз), либо используете любые ресурсы и инструменты для синтезирования искусственного голоса максимально приближенный к реальному.
```

2022-05-04 13:41 UTC, jsohex commented on contributing.md
> +Ссылки на видосы скинуть в дискорд в канал соотсвествующий и опубликовать в твитере. Текст "Hello, we have done 50% of X fork. See videos. From the users side: (link). From the admin's side: (link) .
```suggestion
Ссылки на видео нужно скинуть в дискорд в соотвествующий канал и опубликовать в твиттере. 
Текст "Hello, we have done 50% of development progress a {название продукта} fork. Watch videos: the user usage (link) and the admin usage (link) . This product added to "presale" tab on dash.onout.org. Presale price - $700. Estimate time for releasing is around 1 month. Cheers!"
```

2022-05-04 16:18 UTC, merged