naming
noxonsu/tools.onout.org pull request #45
Opened 2022-05-02 14:39 UTC by noxonsu

2022-05-03 05:57 UTC, NotEternal approved these changes

2022-05-04 14:49 UTC, jsohex requested changes

2022-05-04 14:49 UTC, jsohex commented on contributing.md
> +## 0.1 Нужно переименовать репозиторий так как будет называтся будущий проект. Название не так важно и должно отображать суть продукта, делать его очень просто, выбираем одну основную фукнцию-действи
```suggestion
## 0.1 Переименовываем репозиторий.
Название не так важно и должно отображать суть продукта. Делать его очень просто: выбираем одну основную функцию или действие, которое пользователь совершает в продукте, и вставляем [сюда](https://namelix.com). Понравившийся результат берем за основу. 
```

2022-05-04 14:56 UTC, jsohex approved these changes

2022-05-04 14:58 UTC, shendel approved these changes

2022-05-04 14:59 UTC, merged